
## port config
server:
  port: 8081

## spring config
spring:
  application:
    name: authserver   #
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    ##url: jdbc:mysql://127.0.0.1:3306/authserver?useUnicode=true&amp;characterEncoding=UTF-8
    url: jdbc:mysql://rm-bp185h7kzmkjs6u1h.mysql.rds.aliyuncs.com:3306/uc2?useUnicode=true&characterEncoding=utf-8
    #username: root
    #password: 123
    username: app_developer
    password: D24T5D6EBSuOde8L
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 6
    host: r-bp16feec27433894.redis.rds.aliyuncs.com
    port: 6379
    password: mSmfOelVDk3ZO49y
    pool:
    max-active: 300
    max-wait: 100000
    max-idle: 100
    min-idle: 0
    #timeout: 60000

##log for input
logging:
  level:
    org.springframework.security: DEBUG