mpm:
  configcenter:
    appName: authserver
    base:
      url: https://config.jifenzhi.info
    enabled: false
    sync-interval-seconds: 30
    sync-type: zookeeper
    remote-config-first: true
    sync-zk-servers: config-zk1.jifenzhi.info:2181,config-zk2.jifenzhi.info:2182,config-zk3.jifenzhi.info:2181
qywx:
  gettokenUri: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  getuserinfoUri: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo
  getJspapiTicketUri: https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket

spring:
  profiles:
    active: dev
  application:
    name: authserver
  messages:
    basename: i18n/messages
    cache-seconds: 3600
    encoding: UTF-8
server:
  port: 8082
  session:
    timeout: 7200
eureka:
  client:
    serviceUrl:
      defaultZone: ${mpm.registercenter}
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
logging:
  config: classpath:logback-spring.xml
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: white
    to: white
  border:
    enabled: false
    color: black
    thickness: 1
